### ISSUE TITLE
Developer Console: IllegalArgumentException: Invalid format: "mythssd_2013-03-29"

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#142]
As of this writing, there are 2 entries like this on the Developer Console. It appears
to me that user(s) are putting an underscore in their hostname )an invalid choice per:
http://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_host_names .)

This prevents ProgramGuideCleanupService from developing a valid timestamp.

<pre>
java.lang.IllegalArgumentException: Invalid format: "mythssd_2013-03-29"
at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:747)
at org.joda.time.convert.StringConverter.getInstantMillis(StringConverter.java:65)
at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:171)
at org.joda.time.DateTime.<init>(DateTime.java:241)
at org.mythtv.service.guide.ProgramGuideCleanupService.cleanup(ProgramGuideCleanupService.java:85)
at org.mythtv.service.guide.ProgramGuideCleanupService.onHandleIntent(ProgramGuideCleanupService.java:60)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.os.HandlerThread.run(HandlerThread.java:60)
</pre>

**Comment by dmfrey** [comment]
Thanks, I will look into it.

**Comment by dmfrey** [comment]
there is no more ProgramGuideCleanupService that is actively running.  Anyway we can test this out and verify it is still an issue?

**Comment by billmeek** [comment]
Running on: mythtv-android-frontend-1.10.1-414-g6745950. There are no files
in .../data/org.mythtv/cache. Marking as closed and hiding the report on the
Developer Console.
