### ISSUE TITLE
On startup, Fatal Exception, IllegalStateException

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#177]
To Duplicate:

```
With MAF running,
Choose a page (Status and tMythMote Numbers were tested)
Let the device timeout and turn its screen off
Start MAF from Eclipse
Note Fatal Exception
```

```
09-14 22:32:50.497: V/LocationProfileDaoHelper(30020): resetConnectedProfiles : reset all connected location profiles
09-14 22:32:50.687: V/MainApplication(30088): onCreate : exit
09-14 22:32:50.687: D/BackendStatusService(30088): onHandleIntent : enter
09-14 22:32:50.817: V/NavigationDrawerActivity(30020): onProfileChanged : enter
09-14 22:32:50.817: V/NavigationDrawerActivity(30020): updateContent : enter
09-14 22:32:50.817: V/NavigationDrawerActivity(30020): updateContent : fragment=org.mythtv.client.ui.BackendStatusFragment
09-14 22:32:50.817: D/AndroidRuntime(30020): Shutting down VM
09-14 22:32:50.817: W/dalvikvm(30020): threadid=1: thread exiting with uncaught exception (group=0x40c401f8)
09-14 22:32:50.817: E/AndroidRuntime(30020): FATAL EXCEPTION: main
09-14 22:32:50.817: E/AndroidRuntime(30020): java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
09-14 22:32:50.817: E/AndroidRuntime(30020):    at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1343)
09-14 22:32:50.817: E/AndroidRuntime(30020):    at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1354)
09-14 22:32:50.817: E/AndroidRuntime(30020):    at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:595)
09-14 22:32:50.817: E/AndroidRuntime(30020):    at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:574)
09-14 22:32:50.817: E/AndroidRuntime(30020):    at org.mythtv.client.ui.NavigationDrawerActivity.updateContent(NavigationDrawerActivity.java:340)
09-14 22:32:50.817: E/AndroidRuntime(30020):    at org.mythtv.client.ui.NavigationDrawerActivity.access$2(NavigationDrawerActivity.java:333)
09-14 22:32:50.817: E/AndroidRuntime(30020):    at org.mythtv.client.ui.NavigationDrawerActivity$1.onProfileChanged(NavigationDrawerActivity.java:79)
09-14 22:32:50.817: E/AndroidRuntime(30020):    at org.mythtv.client.ui.navigationDrawer.ProfileRow$ConnectBackendTask.onPostExecute(ProfileRow.java:311)
09-14 22:32:50.817: E/AndroidRuntime(30020):    at org.mythtv.client.ui.navigationDrawer.ProfileRow$ConnectBackendTask.onPostExecute(ProfileRow.java:1)
09-14 22:32:50.817: E/AndroidRuntime(30020):    at android.os.AsyncTask.finish(AsyncTask.java:602)
09-14 22:32:50.817: E/AndroidRuntime(30020):    at android.os.AsyncTask.access$600(AsyncTask.java:156)
09-14 22:32:50.817: E/AndroidRuntime(30020):    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:615)
09-14 22:32:50.817: E/AndroidRuntime(30020):    at android.os.Handler.dispatchMessage(Handler.java:99)
09-14 22:32:50.817: E/AndroidRuntime(30020):    at android.os.Looper.loop(Looper.java:137)
09-14 22:32:50.817: E/AndroidRuntime(30020):    at android.app.ActivityThread.main(ActivityThread.java:4507)
09-14 22:32:50.817: E/AndroidRuntime(30020):    at java.lang.reflect.Method.invokeNative(Native Method)
09-14 22:32:50.817: E/AndroidRuntime(30020):    at java.lang.reflect.Method.invoke(Method.java:511)
09-14 22:32:50.817: E/AndroidRuntime(30020):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:978)
09-14 22:32:50.817: E/AndroidRuntime(30020):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
09-14 22:32:50.817: E/AndroidRuntime(30020):    at dalvik.system.NativeStart.main(Native Method)
09-14 22:32:50.827: I/BackendStatusService(30088): onHandleIntent : DOWNLOAD action selected
09-14 22:32:50.827: D/BackendStatusHelperV27(30088): process : enter
```

**Comment by dmfrey** [comment]
What screen were you on when you got this exception.

As a design discussion, should we consider going back to the status screen upon waking up from idle?

**Comment by pot8oe** [comment]
I think we should go back to the begining status screen. At least after a
prolonged period of not running the app.

**Comment by billmeek** [comment]
@dmfrey:
I never saw a MAF screen when I turned my tablet's screen back
on. Normally, I verify that the screen is on and that an existing run
of MAF has exited. I'll try combinations of screen on/off and try
letting the screen turn off on various MAF screens.

**Comment by billmeek** [comment]
I'll edit the original issue with a to duplicate sequence of:
Choose a page (Status and MythMote Numbers were tested)
Let the device timeout and turn the screen off
Start MAF from Eclipse
Note Fatal Exception
Changing status to bug, but not critical

**Comment by dmfrey** [comment]
I found out why this is happening...

This article gives a good breakdown as to why this occurs: http://www.androiddesignpatterns.com/2013/08/fragment-transaction-commit-state-loss.html

I am, in fact, doing what they mentioned...There is an AsyncTask that calls a callback to the NavigationDrawerActivity.  It gets executed in the AsyncTasks.onPostExecute() method.  But the Activity has gone away and not reloaded yet.  I am considering a fix.
