### ISSUE TITLE
Manage Profiles: Deleting active profile may cause an NPE

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#178]
To Duplicate:

```
Go to the Manage Profiles screen
Delete the active profile (tested with only one profile)
Return to the Status screen
Prompt will warn of no backend profile, dismiss it
Try to return to the Manage Profiles screen
Note NPE
```

```
09-15 22:08:22.938: V/NavigationDrawerActivity(9092): onItemClick : position=2, id=2, oldSelection=2
09-15 22:08:22.938: V/NavigationDrawerActivity(9092): onCreate : starting preferences activity
09-15 22:08:22.958: V/NavigationDrawerActivity(9092): onItemClick : exit
09-15 22:08:22.958: D/FrontendDaoHelper(9092): findAll : enter
09-15 22:08:22.958: D/AndroidRuntime(9092): Shutting down VM
09-15 22:08:22.958: W/dalvikvm(9092): threadid=1: thread exiting with uncaught exception (group=0x40c401f8)
09-15 22:08:22.968: E/AndroidRuntime(9092): FATAL EXCEPTION: main
09-15 22:08:22.968: E/AndroidRuntime(9092): java.lang.NullPointerException
09-15 22:08:22.968: E/AndroidRuntime(9092):     at org.mythtv.db.AbstractDaoHelper.appendLocationHostname(AbstractDaoHelper.java:46)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at org.mythtv.db.frontends.FrontendDaoHelper.findAll(FrontendDaoHelper.java:76)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at org.mythtv.client.ui.navigationDrawer.FrontendsRow.getView(FrontendsRow.java:97)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at org.mythtv.client.ui.NavigationDrawerActivity$NavigationDrawerAdapter.getView(NavigationDrawerActivity.java:412)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at android.widget.AbsListView.obtainView(AbsListView.java:2201)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at android.widget.ListView.makeAndAddView(ListView.java:1774)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at android.widget.ListView.fillDown(ListView.java:672)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at android.widget.ListView.fillSpecific(ListView.java:1330)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at android.widget.ListView.layoutChildren(ListView.java:1603)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at android.widget.AbsListView.onLayout(AbsListView.java:2052)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at android.view.View.layout(View.java:11477)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at android.view.ViewGroup.layout(ViewGroup.java:4232)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:702)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at android.view.View.layout(View.java:11477)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at android.view.ViewGroup.layout(ViewGroup.java:4232)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at android.view.View.layout(View.java:11477)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at android.view.ViewGroup.layout(ViewGroup.java:4232)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1644)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1502)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at android.widget.LinearLayout.onLayout(LinearLayout.java:1415)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at android.view.View.layout(View.java:11477)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at android.view.ViewGroup.layout(ViewGroup.java:4232)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at android.view.View.layout(View.java:11477)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at android.view.ViewGroup.layout(ViewGroup.java:4232)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1692)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2649)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at android.os.Handler.dispatchMessage(Handler.java:99)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at android.os.Looper.loop(Looper.java:137)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at android.app.ActivityThread.main(ActivityThread.java:4507)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at java.lang.reflect.Method.invokeNative(Native Method)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at java.lang.reflect.Method.invoke(Method.java:511)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:978)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
09-15 22:08:22.968: E/AndroidRuntime(9092):     at dalvik.system.NativeStart.main(Native Method)
09-15 22:09:07.828: I/Process(9092): Sending signal. PID: 9092 SIG: 9
```

**Comment by billmeek** [comment]
Still fails on Android 4.0.1 (where I did my original tests.) I just put the
1st few lines of the trace because the line numbers changed. If a
full trace is required, let me know.

```
09-22 13:07:05.666: W/dalvikvm(19382): threadid=1: thread exiting with uncaught exception (group=0x40c471f8)
09-22 13:07:05.666: E/AndroidRuntime(19382): FATAL EXCEPTION: main
09-22 13:07:05.666: E/AndroidRuntime(19382): java.lang.IllegalArgumentException: LocationProfile is required
09-22 13:07:05.666: E/AndroidRuntime(19382):    at org.mythtv.db.frontends.FrontendDaoHelper.findAll(FrontendDaoHelper.java:76)
09-22 13:07:05.666: E/AndroidRuntime(19382):    at org.mythtv.client.ui.navigationDrawer.FrontendsRow.getView(FrontendsRow.java:97)
09-22 13:07:05.666: E/AndroidRuntime(19382):    at org.mythtv.client.ui.NavigationDrawerActivity$NavigationDrawerAdapter.getView(NavigationDrawerActivity.java:429)
09-22 13:07:05.666: E/AndroidRuntime(19382):    at android.widget.AbsListView.obtainView(AbsListView.java:2201)
```

On a 7" Android 4.1.2 tablet, it dosn't fail.

**Comment by dmfrey** [comment]
I will fire up a 4.0.1 vm later tonight and see what is going on

**Comment by billmeek** [comment]
A-OK, thanks! Another edge case closed.
