### ISSUE TITLE
Fatal Exception immediately after downloading the app from Eclipse.

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#188]
New with 9/25/2013 commits. Android 4.1.2

```
09-25 16:55:10.120: I/ProfileRow(4567): ConnectBackendTask.onPostExecute : master backend connected
09-25 16:55:10.220: V/LocationProfileDaoHelper(4567): resetConnectedProfiles : reset all connected location profiles
09-25 16:55:10.280: V/NavigationDrawerActivity(4567): onProfileChanged : enter
09-25 16:55:10.280: V/NavigationDrawerActivity(4567): updateContent : enter
09-25 16:55:10.280: V/NavigationDrawerActivity(4567): updateContent : fragment=org.mythtv.client.ui.BackendStatusFragment
09-25 16:55:10.280: V/NavigationDrawerActivity(4567): updateContent : weak reference to activity available
09-25 16:55:10.280: D/AndroidRuntime(4567): Shutting down VM
09-25 16:55:10.280: W/dalvikvm(4567): threadid=1: thread exiting with uncaught exception (group=0x40c471f8)
09-25 16:55:10.280: E/AndroidRuntime(4567): FATAL EXCEPTION: main
09-25 16:55:10.280: E/AndroidRuntime(4567): java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
09-25 16:55:10.280: E/AndroidRuntime(4567):     at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1343)
09-25 16:55:10.280: E/AndroidRuntime(4567):     at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1354)
09-25 16:55:10.280: E/AndroidRuntime(4567):     at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:595)
09-25 16:55:10.280: E/AndroidRuntime(4567):     at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:574)
09-25 16:55:10.280: E/AndroidRuntime(4567):     at org.mythtv.client.ui.NavigationDrawerActivity.updateContent(NavigationDrawerActivity.java:355)
09-25 16:55:10.280: E/AndroidRuntime(4567):     at org.mythtv.client.ui.NavigationDrawerActivity.access$2(NavigationDrawerActivity.java:345)
09-25 16:55:10.280: E/AndroidRuntime(4567):     at org.mythtv.client.ui.NavigationDrawerActivity$1.onProfileChanged(NavigationDrawerActivity.java:82)
09-25 16:55:10.280: E/AndroidRuntime(4567):     at org.mythtv.client.ui.navigationDrawer.ProfileRow$ConnectBackendTask.onPostExecute(ProfileRow.java:312)
09-25 16:55:10.280: E/AndroidRuntime(4567):     at org.mythtv.client.ui.navigationDrawer.ProfileRow$ConnectBackendTask.onPostExecute(ProfileRow.java:1)
09-25 16:55:10.280: E/AndroidRuntime(4567):     at android.os.AsyncTask.finish(AsyncTask.java:602)
09-25 16:55:10.280: E/AndroidRuntime(4567):     at android.os.AsyncTask.access$600(AsyncTask.java:156)
09-25 16:55:10.280: E/AndroidRuntime(4567):     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:615)
09-25 16:55:10.280: E/AndroidRuntime(4567):     at android.os.Handler.dispatchMessage(Handler.java:99)
09-25 16:55:10.280: E/AndroidRuntime(4567):     at android.os.Looper.loop(Looper.java:137)
09-25 16:55:10.280: E/AndroidRuntime(4567):     at android.app.ActivityThread.main(ActivityThread.java:4507)
09-25 16:55:10.280: E/AndroidRuntime(4567):     at java.lang.reflect.Method.invokeNative(Native Method)
09-25 16:55:10.280: E/AndroidRuntime(4567):     at java.lang.reflect.Method.invoke(Method.java:511)
09-25 16:55:10.280: E/AndroidRuntime(4567):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:978)
09-25 16:55:10.280: E/AndroidRuntime(4567):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
09-25 16:55:10.280: E/AndroidRuntime(4567):     at dalvik.system.NativeStart.main(Native Method)
09-25 16:55:10.340: D/dalvikvm(4637): GC_CONCURRENT freed 654K, 11% free 8356K/9287K, paused 2ms+2ms
09-25 16:55:10.380: I/Process(4567): Sending signal. PID: 4567 SIG: 9
```

**Comment by billmeek** [comment]
I saw this exactly once and couldn't duplicate it at will. And, I've
tested the same way with this fix and can't get it to fail. Closing.
