### ISSUE TITLE
Scan Network: Fatal Exception/NPE during backend scanning

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#192]
Deleted all profiles
Scanned Network
NPE fired
First noticed today

```
09-25 23:08:25.789: W/dalvikvm(10853): threadid=16: thread exiting with uncaught exception (group=0x418442a0)
09-25 23:08:25.812: E/AndroidRuntime(10853): FATAL EXCEPTION: AsyncTask #1
09-25 23:08:25.812: E/AndroidRuntime(10853): java.lang.RuntimeException: An error occured while executing doInBackground()
09-25 23:08:25.812: E/AndroidRuntime(10853):    at android.os.AsyncTask$3.done(AsyncTask.java:299)
09-25 23:08:25.812: E/AndroidRuntime(10853):    at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
09-25 23:08:25.812: E/AndroidRuntime(10853):    at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
09-25 23:08:25.812: E/AndroidRuntime(10853):    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
09-25 23:08:25.812: E/AndroidRuntime(10853):    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
09-25 23:08:25.812: E/AndroidRuntime(10853):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
09-25 23:08:25.812: E/AndroidRuntime(10853):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
09-25 23:08:25.812: E/AndroidRuntime(10853):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
09-25 23:08:25.812: E/AndroidRuntime(10853):    at java.lang.Thread.run(Thread.java:856)
09-25 23:08:25.812: E/AndroidRuntime(10853): Caused by: java.lang.NullPointerException
09-25 23:08:25.812: E/AndroidRuntime(10853):    at org.mythtv.service.myth.GetHostnameTask.doInBackground(GetHostnameTask.java:117)
09-25 23:08:25.812: E/AndroidRuntime(10853):    at org.mythtv.service.myth.GetHostnameTask.doInBackground(GetHostnameTask.java:1)
09-25 23:08:25.812: E/AndroidRuntime(10853):    at android.os.AsyncTask$2.call(AsyncTask.java:287)
09-25 23:08:25.812: E/AndroidRuntime(10853):    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
09-25 23:08:25.812: E/AndroidRuntime(10853):    ... 5 more
09-25 23:08:36.101: I/Choreographer(10853): Skipped 613 frames!  The application may be doing too much work on its main thread.
```

**Comment by billmeek** [comment]
Tested on both my tablets. A-OK, so closing.

@dmfrey, I'll let you craft a new issue to address adding similar
fixes as mentioned in the commit.
