### ISSUE TITLE
Recordings: Fatal Exception/NPE

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#196]
Seen exactly one time after on latest commit. Starting
MAF a 2nd time, didn't fail.

```
09-26 12:47:17.164: V/ProgramGroupDaoHelper(17281): findOne : exit
09-26 12:47:17.171: D/AndroidRuntime(17281): Shutting down VM
09-26 12:47:17.171: W/dalvikvm(17281): threadid=1: thread exiting with uncaught exception (group=0x418442a0)
09-26 12:47:17.171: E/AndroidRuntime(17281): FATAL EXCEPTION: main
09-26 12:47:17.171: E/AndroidRuntime(17281): java.lang.RuntimeException: Error receiving broadcast Intent { act=org.mythtv.background.recorded.ACTION_COMPLETE flg=0x10 (has extras) } in org.mythtv.client.ui.dvr.EpisodeFragment$RecordedRemovedReceiver@426c51e8
09-26 12:47:17.171: E/AndroidRuntime(17281):    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:765)
09-26 12:47:17.171: E/AndroidRuntime(17281):    at android.os.Handler.handleCallback(Handler.java:615)
09-26 12:47:17.171: E/AndroidRuntime(17281):    at android.os.Handler.dispatchMessage(Handler.java:92)
09-26 12:47:17.171: E/AndroidRuntime(17281):    at android.os.Looper.loop(Looper.java:137)
09-26 12:47:17.171: E/AndroidRuntime(17281):    at android.app.ActivityThread.main(ActivityThread.java:4949)
09-26 12:47:17.171: E/AndroidRuntime(17281):    at java.lang.reflect.Method.invokeNative(Native Method)
09-26 12:47:17.171: E/AndroidRuntime(17281):    at java.lang.reflect.Method.invoke(Method.java:511)
09-26 12:47:17.171: E/AndroidRuntime(17281):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1043)
09-26 12:47:17.171: E/AndroidRuntime(17281):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
09-26 12:47:17.171: E/AndroidRuntime(17281):    at dalvik.system.NativeStart.main(Native Method)
09-26 12:47:17.171: E/AndroidRuntime(17281): Caused by: java.lang.NullPointerException
09-26 12:47:17.171: E/AndroidRuntime(17281):    at org.mythtv.client.ui.dvr.RecordingsParentFragment.onEpisodeDeleted(RecordingsParentFragment.java:304)
09-26 12:47:17.171: E/AndroidRuntime(17281):    at org.mythtv.client.ui.dvr.EpisodeFragment$RecordedRemovedReceiver.onReceive(EpisodeFragment.java:731)
09-26 12:47:17.171: E/AndroidRuntime(17281):    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:755)
09-26 12:47:17.171: E/AndroidRuntime(17281):    ... 9 more
```

**Comment by pot8oe** [comment]
@dmfrey was this fixed in 6d735850710cbf00567ff03d883b0af8f3a0d59a ?

**Comment by dmfrey** [comment]
I will have to review the commit.

**Comment by pot8oe** [comment]
@dmfrey I ask because there is a check for null at the offending line RecordingsParentFragment.java:304

**Comment by dmfrey** [comment]
That is probably it, but at the I don't think there was a ticket in for it

**Comment by dmfrey** [comment]
retest #196 

marking for retesting

**Comment by billmeek** [comment]
Given that I only saw this once that the the previously mentioned
commit references RecordingsParentFragment.onEpisodeDeleted
closing.
