### ISSUE TITLE
Fatal Exception: IllegalStateException when undefined host came on-line

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#217]
May be the same as #177. This one fired when a previously undefined
BE came on-line. I pressed Save. The difference is when it happened.

```
10-06 18:00:49.687: V/LocationProfileEditor(20848): onGetHostnameTaskFinished : saving hostname 'mc1'
10-06 18:00:49.718: V/LocationProfileEditor(20848): profile=LocationProfile [id=2, type=HOME, name=Mythbackend on mc1, url=http://192.168.1.223:6544/, selected=true, connected=false, version=v027, wolAddress=, hostname=mc1, ]
10-06 18:00:49.734: D/GetHostnameTask(20848): onPostExecute : exit
10-06 18:00:49.812: D/AndroidRuntime(20848): Shutting down VM
10-06 18:00:49.812: W/dalvikvm(20848): threadid=1: thread exiting with uncaught exception (group=0x40da92a0)
10-06 18:00:49.812: E/AndroidRuntime(20848): FATAL EXCEPTION: main
10-06 18:00:49.812: E/AndroidRuntime(20848): java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
10-06 18:00:49.812: E/AndroidRuntime(20848):    at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1343)
10-06 18:00:49.812: E/AndroidRuntime(20848):    at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1354)
10-06 18:00:49.812: E/AndroidRuntime(20848):    at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:595)
10-06 18:00:49.812: E/AndroidRuntime(20848):    at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:574)
10-06 18:00:49.812: E/AndroidRuntime(20848):    at org.mythtv.client.ui.BackendStatusFragment.onConfigurationChanged(BackendStatusFragment.java:320)
10-06 18:00:49.812: E/AndroidRuntime(20848):    at android.support.v4.app.Fragment.performConfigurationChanged(Fragment.java:1533)
10-06 18:00:49.812: E/AndroidRuntime(20848):    at android.support.v4.app.FragmentManagerImpl.dispatchConfigurationChanged(FragmentManager.java:1925)
10-06 18:00:49.812: E/AndroidRuntime(20848):    at android.support.v4.app.FragmentActivity.onConfigurationChanged(FragmentActivity.java:190)
10-06 18:00:49.812: E/AndroidRuntime(20848):    at android.app.ActivityThread.performConfigurationChanged(ActivityThread.java:3694)
10-06 18:00:49.812: E/AndroidRuntime(20848):    at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:3868)
10-06 18:00:49.812: E/AndroidRuntime(20848):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
10-06 18:00:49.812: E/AndroidRuntime(20848):    at android.os.Handler.dispatchMessage(Handler.java:99)
10-06 18:00:49.812: E/AndroidRuntime(20848):    at android.os.Looper.loop(Looper.java:137)
10-06 18:00:49.812: E/AndroidRuntime(20848):    at android.app.ActivityThread.main(ActivityThread.java:4949)
10-06 18:00:49.812: E/AndroidRuntime(20848):    at java.lang.reflect.Method.invokeNative(Native Method)
10-06 18:00:49.812: E/AndroidRuntime(20848):    at java.lang.reflect.Method.invoke(Method.java:511)
10-06 18:00:49.812: E/AndroidRuntime(20848):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1043)
10-06 18:00:49.812: E/AndroidRuntime(20848):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
10-06 18:00:49.812: E/AndroidRuntime(20848):    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by billmeek** [comment]
Closing. This was another edge case that I wasn't able to duplicate.
I repeated the steps to the original report and had no problems.
