### ISSUE TITLE
Developer Console: 1.20.0 beta, RuntimeException: Unable to start activity

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#220]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mythtv/org.mythtv.client.ui.dvr.DvrNavigationDrawerActivity}: java.lang.IllegalArgumentException: LocationProfile is required
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
at android.app.ActivityThread.access$600(ActivityThread.java:141)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5103)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: LocationProfile is required
at org.mythtv.db.http.EtagDaoHelper.findByEndpointAndDataId(EtagDaoHelper.java:223)
at org.mythtv.client.ui.dvr.DvrNavigationDrawerActivity$DvrNavigationDrawerAdapter.setupRowsList(DvrNavigationDrawerActivity.java:465)
at org.mythtv.client.ui.dvr.DvrNavigationDrawerActivity$DvrNavigationDrawerAdapter.<init>(DvrNavigationDrawerActivity.java:393)
at org.mythtv.client.ui.dvr.DvrNavigationDrawerActivity.onCreate(DvrNavigationDrawerActivity.java:97)
at android.app.Activity.performCreate(Activity.java:5133)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
```

**Comment by dmfrey** [comment]
I am not sure how they are getting to here if they didn't select a location profile.  However I have added some try catches around those blocks.

**Comment by billmeek** [comment]
Couldn't reproduce it. Tried deleting the DB and scanning, then
deleting the DB and manually adding a Home profile. Then trying
to open the Navigation drawer each time.

**Comment by dmfrey** [comment]
One thing to try...
1. create either a Home or Away profile, but not the other.
2. Let it connect and refresh the DB.
3. Open the Nav Drawer and switch the toggle to the one not created.
4. Close the message indicating that no profile found
5. Is the nav drawer still showing DVR and Multimedia links?
   - If so, can you click them?

On Thu, Oct 10, 2013 at 3:12 PM, billmeek notifications@github.com wrote:

> Couldn't reproduce it. Tried deleting the DB and scanning, then
> deleting the DB and manually adding a Home profile. Then trying
> to open the Navigation drawer each time.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/220#issuecomment-26082302
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
Answer to step 5, yes and yes. Also, returning from the
Multimedia page to the Status screen and then looking
at the nav drawer, Home is once again selected.

The above done without the fix. Leaving Closed.

**Comment by dmfrey** [comment]
reopen #220

On Thu, Oct 10, 2013 at 3:38 PM, billmeek notifications@github.com wrote:

> Answer to step 5, yes and yes. Also, returning from the
> Multimedia page to the Status screen and then looking
> at the nav drawer, Home is once again selected.
> 
> The above done without the fix. Leaving Closed.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/220#issuecomment-26084267
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey
