### ISSUE TITLE
Developer Console: 1.20.0 beta, NPE in GalleryGridAdapter.java:111 similar to #220

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#221]
Similar to #220, but in Gallery.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mythtv/org.mythtv.client.ui.media.MediaNavigationDrawerActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2337)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
at android.app.ActivityThread.access$600(ActivityThread.java:150)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5257)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at org.mythtv.client.ui.media.GalleryGridAdapter.<init>(GalleryGridAdapter.java:111)
at org.mythtv.client.ui.media.PicturesParentFragment.onActivityCreated(PicturesParentFragment.java:74)
at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1486)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1460)
at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:556)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
at android.app.Activity.performStart(Activity.java:5143)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2300)
... 11 more
```

**Comment by dmfrey** [comment]
This issue and issue #220 are really evidence of a bigger problem...

The nav drawer is not cleaning up its options when not connected.  I think
this needs to be a new issue and these can then be closed when that issue
is completed.

On Thu, Oct 10, 2013 at 3:19 PM, billmeek notifications@github.com wrote:

> Similar to #220https://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/220,
> but in Gallery.
> 
> java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mythtv/org.mythtv.client.ui.media.MediaNavigationDrawerActivity}: java.lang.NullPointerException
> at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2337)
> at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
> at android.app.ActivityThread.access$600(ActivityThread.java:150)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266)
> at android.os.Handler.dispatchMessage(Handler.java:99)
> at android.os.Looper.loop(Looper.java:137)
> at android.app.ActivityThread.main(ActivityThread.java:5257)
> at java.lang.reflect.Method.invokeNative(Native Method)
> at java.lang.reflect.Method.invoke(Method.java:525)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
> at dalvik.system.NativeStart.main(Native Method)
> Caused by: java.lang.NullPointerException
> at org.mythtv.client.ui.media.GalleryGridAdapter.<init>(GalleryGridAdapter.java:111)
> at org.mythtv.client.ui.media.PicturesParentFragment.onActivityCreated(PicturesParentFragment.java:74)
> at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1486)
> at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
> at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
> at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
> at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1460)
> at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:556)
> at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
> at android.app.Activity.performStart(Activity.java:5143)
> at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2300)
> ... 11 more
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/221
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey
