### ISSUE TITLE
1.20.0 beta: Crash on exit (NullPointerException in ProgramGroupFragment.onSaveInstanceState)

### ISSUE THREAD

**Issue by Speckto** [MythTV-Clients/MythTV-Android-Frontend#230]
I have a Nexus 10 device and I am running android 4.3. With the beta, I get a repeatable crash on exit if I do the following:
1. Start the application and allow it to load the home screen (with the upcoming recordings, and recording status)
2. Tap the myth icon in the top left, select 'DVR' from the actions screen (this drops me at a blank recordings screen - see note below)
3. Tap the myth icon in the top left, Select 'Guide' from the side bar
4. Tap the myth icon in the top left, Select 'Recordings' from the side bar
5. Tap the home button. The application hides then I get "Unfortunately MythTV android Frontend has stopped". 

There is a null pointer exception in the log file.

I've uploaded a log from that session here (filtered on pid):
http://random.divergentlocus.co.uk/filedump/myth-exit-crash-pid.txt

Extract of the crash:

```
10-13 19:19:42.864: I/ProgramGroupFragment(8858): onSaveInstanceState : enter
10-13 19:19:42.864: D/AndroidRuntime(8858): Shutting down VM
10-13 19:19:42.864: W/dalvikvm(8858): threadid=1: thread exiting with uncaught exception (group=0x4150a700)
10-13 19:19:42.869: E/AndroidRuntime(8858): FATAL EXCEPTION: main
10-13 19:19:42.869: E/AndroidRuntime(8858): java.lang.NullPointerException
10-13 19:19:42.869: E/AndroidRuntime(8858):     at org.mythtv.client.ui.dvr.ProgramGroupFragment.onSaveInstanceState(ProgramGroupFragment.java:189)
10-13 19:19:42.869: E/AndroidRuntime(8858):     at android.support.v4.app.Fragment.performSaveInstanceState(Fragment.java:1625)
10-13 19:19:42.869: E/AndroidRuntime(8858):     at android.support.v4.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:1603)
10-13 19:19:42.869: E/AndroidRuntime(8858):     at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:1671)
10-13 19:19:42.869: E/AndroidRuntime(8858):     at android.support.v4.app.Fragment.performSaveInstanceState(Fragment.java:1627)
10-13 19:19:42.869: E/AndroidRuntime(8858):     at android.support.v4.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:1603)
10-13 19:19:42.869: E/AndroidRuntime(8858):     at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:1671)
10-13 19:19:42.869: E/AndroidRuntime(8858):     at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:532)
10-13 19:19:42.869: E/AndroidRuntime(8858):     at org.mythtv.client.ui.dvr.DvrNavigationDrawerActivity.onSaveInstanceState(DvrNavigationDrawerActivity.java:317)
10-13 19:19:42.869: E/AndroidRuntime(8858):     at android.app.Activity.performSaveInstanceState(Activity.java:1147)
10-13 19:19:42.869: E/AndroidRuntime(8858):     at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1223)
10-13 19:19:42.869: E/AndroidRuntime(8858):     at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3177)
10-13 19:19:42.869: E/AndroidRuntime(8858):     at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3236)
10-13 19:19:42.869: E/AndroidRuntime(8858):     at android.app.ActivityThread.access$900(ActivityThread.java:141)
10-13 19:19:42.869: E/AndroidRuntime(8858):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
10-13 19:19:42.869: E/AndroidRuntime(8858):     at android.os.Handler.dispatchMessage(Handler.java:99)
10-13 19:19:42.869: E/AndroidRuntime(8858):     at android.os.Looper.loop(Looper.java:137)
10-13 19:19:42.869: E/AndroidRuntime(8858):     at android.app.ActivityThread.main(ActivityThread.java:5103)
10-13 19:19:42.869: E/AndroidRuntime(8858):     at java.lang.reflect.Method.invokeNative(Native Method)
10-13 19:19:42.869: E/AndroidRuntime(8858):     at java.lang.reflect.Method.invoke(Method.java:525)
10-13 19:19:42.869: E/AndroidRuntime(8858):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
10-13 19:19:42.869: E/AndroidRuntime(8858):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
10-13 19:19:42.869: E/AndroidRuntime(8858):     at dalvik.system.NativeStart.main(Native Method)
10-13 19:20:10.424: I/Process(8858): Sending signal. PID: 8858 SIG: 9
```

Note: I currently have an issue where the recordings screen is empty even though I have recordings - this is being handled under issue #219. When the android front-end retrieves the recordings it throws an exception due to incorrect character encodings when decoding the json data. I mention this because it could be this crash only occurs after the recordings failed to be parsed.

**Comment by billmeek** [comment]
Thanks for reporting. Labled as bug/critical.

**Comment by billmeek** [comment]
Works for me, but I couldn't duplicate it.

@Speckto, please test when 1.20.2 is released (you'll see the real version at the top of the Navigation Drawer.)
Thanks.

**Comment by Speckto** [comment]
I have retested this with the 1.20.2 beta and can confirm that the crash on exit no longer occurs. From my perspective this appears to have been resolved. Feel free to close this issue - I leave it open in case you have further tracking to do against it.

Thanks for your efforts in fixing this!

**Comment by billmeek** [comment]
Great news. Thanks for testing! Closing
