### ISSUE TITLE
Developer Console: 1.20.1: DvrNavigationDrawerActivity: java.lang.NullPointerException

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#231]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mythtv/org.mythtv.client.ui.dvr.DvrNavigationDrawerActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2351)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
at android.app.ActivityThread.access$600(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1331)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:155)
at android.app.ActivityThread.main(ActivityThread.java:5454)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at org.mythtv.client.ui.dvr.RecordingsFragment.onCreateLoader(RecordingsFragment.java:116)
at android.support.v4.app.LoaderManagerImpl.createLoader(LoaderManager.java:490)
at android.support.v4.app.LoaderManagerImpl.createAndInstallLoader(LoaderManager.java:499)
at android.support.v4.app.LoaderManagerImpl.initLoader(LoaderManager.java:553)
at org.mythtv.client.ui.dvr.RecordingsFragment.onActivityCreated(RecordingsFragment.java:174)
at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1486)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1460)
at android.support.v4.app.Fragment.performStart(Fragment.java:1499)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:957)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086)
at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:1882)
at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:573)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1225)
at android.app.Activity.performStart(Activity.java:5076)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2324)
... 11 more
```

**Comment by dmfrey** [comment]
I believe this is related to issue #223

**Comment by billmeek** [comment]
Closing because I closed 233 and the comment above.
