### ISSUE TITLE
Developer Console: 1.20.3; RuntimeException: Error receiving broadcast Intent 

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#239]
```
java.lang.RuntimeException: Error receiving broadcast Intent { act=org.mythtv.background.status.ACTION_COMPLETE flg=0x10 (has extras) } in org.mythtv.client.ui.BackendStatusFragment$BackendStatusReceiver@41ebe160
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:767)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5021)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at org.mythtv.client.ui.BackendStatusFragment.startFrontendDiscoveryService(BackendStatusFragment.java:647)
at org.mythtv.client.ui.BackendStatusFragment.checkFrontendDiscoveryService(BackendStatusFragment.java:641)
at org.mythtv.client.ui.BackendStatusFragment.access$2(BackendStatusFragment.java:639)
at org.mythtv.client.ui.BackendStatusFragment$BackendStatusReceiver.onReceive(BackendStatusFragment.java:748)
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:757)
```

**Comment by billmeek** [comment]
Re-hid in the Developer Console. Closing
