### ISSUE TITLE
NPE in onBackendStatusUpdated (BackendStatusFragment.java:496)

### ISSUE THREAD

**Issue by wronka** [MythTV-Clients/MythTV-Android-Frontend#267]
I recently wiped my phone (Nexus 4/mako) and reflashed with CM11/Android 4.4 from November 23rdish.  I think the client was previously working, but I'm not sure if that was with CM11 or 10.2, so I can't tack this down to being a change in data on the Myth server or a change in environment.

V/BackendStatusHelperV25(11464): updateProgramGuide : enter
V/BackendStatusHelperV25(11464): updateProgramGuide : exit
V/BackendStatusHelperV25(11464): convertBackendStatus : enter
V/BackendStatusHelperV25(11464): convertBackendStatus : exit
D/BackendStatusHelperV25(11464): process : exit
V/BackendStatusService(11464): sendComplete : enter
V/BackendStatusService(11464): sendComplete : exit
D/BackendStatusService(11464): onHandleIntent : exit
V/BackendStatusFragment(13498): BackendStatusReceiver.onReceive : enter
I/BackendStatusFragment(13498): BackendStatusReceiver.onReceive : Backend Status Download Service Finished
D/AndroidRuntime(13498): Shutting down VM
W/dalvikvm(13498): threadid=1: thread exiting with uncaught exception (group=0x41dedce0)
E/AndroidRuntime(13498): FATAL EXCEPTION: main
E/AndroidRuntime(13498): Process: org.mythtv, PID: 13498
E/AndroidRuntime(13498): java.lang.RuntimeException: Error receiving broadcast Intent { act=org.mythtv.background.status.ACTION_COMPLETE flg=0x10 (has extras) } in org.mythtv.client.ui.BackendStatusFragment$BackendStatusReceiver@429c8350
E/AndroidRuntime(13498):        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:776)
E/AndroidRuntime(13498):        at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(13498):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(13498):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(13498):        at android.app.ActivityThread.main(ActivityThread.java:5146)
E/AndroidRuntime(13498):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(13498):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(13498):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
E/AndroidRuntime(13498):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
E/AndroidRuntime(13498):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(13498): Caused by: java.lang.NullPointerException
E/AndroidRuntime(13498):        at org.mythtv.client.ui.BackendStatusFragment.onBackendStatusUpdated(BackendStatusFragment.java:496)
E/AndroidRuntime(13498):        at org.mythtv.client.ui.BackendStatusFragment.access$1(BackendStatusFragment.java:436)
E/AndroidRuntime(13498):        at org.mythtv.client.ui.BackendStatusFragment$BackendStatusReceiver.onReceive(BackendStatusFragment.java:834)
E/AndroidRuntime(13498):        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:766)
E/AndroidRuntime(13498):        ... 9 more
W/ActivityManager( 1603):   Force finishing activity org.mythtv/.client.ui.NavigationDrawerActivity
W/ActivityManager( 1603): Activity pause timeout for ActivityRecord{42daae78 u0 org.mythtv/.client.ui.NavigationDrawerActivity t120 f}
I/ActivityManager( 1603): Config changes=480 {1.0 310mcc260mnc en_US ldltr sw384dp w384dp h567dp 320dpi nrml port finger -keyb/v/h -nav/h s.93 themeR

**Comment by wronka** [comment]
I added && ­guide.getGuideThru() != null to the conditional which allowed the intent to finish loading.
