### ISSUE TITLE
Google Play Issue - JodaTime Illegal Instant due to Timezone offset

### ISSUE THREAD

**Issue by dmfrey** [MythTV-Clients/MythTV-Android-Frontend#54]
java.lang.IllegalArgumentException: Cannot parse "2012-10-21": Illegal instant due to time zone offset transition (America/Sao_Paulo)
at org.joda.time.format.DateTimeParserBucket.computeMillis(DateTimeParserBucket.java:390)
at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:742)
at org.joda.time.convert.StringConverter.getInstantMillis(StringConverter.java:65)
at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:171)
at org.joda.time.DateTime.<init>(DateTime.java:241)
at org.mythtv.service.guide.ProgramGuideCleanupService.cleanup(ProgramGuideCleanupService.java:86)
at org.mythtv.service.guide.ProgramGuideCleanupService.onHandleIntent(ProgramGuideCleanupService.java:60)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:59)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:123)
at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by dmfrey** [comment]
this appears to be a rare daylight savings issue.  I checked the Google Play console and it doesn't appear to have happened in quite some time.  Recommend closing for now.
