### ISSUE TITLE
Google Play Issue - Compare failed

### ISSUE THREAD

**Issue by dmfrey** [MythTV-Clients/MythTV-Android-Frontend#56]
java.lang.IllegalArgumentException: Comparison method violates its general contract!
at java.util.ComparableTimSort.mergeLo(ComparableTimSort.java:710)
at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:447)
at java.util.ComparableTimSort.mergeForceCollapse(ComparableTimSort.java:388)
at java.util.ComparableTimSort.sort(ComparableTimSort.java:187)
at java.util.ComparableTimSort.sort(ComparableTimSort.java:142)
at java.util.Arrays.sort(Arrays.java:1973)
at java.util.Collections.sort(Collections.java:1867)
at org.mythtv.service.guide.ProgramGuideDownloadService.process(ProgramGuideDownloadService.java:204)
at org.mythtv.service.guide.ProgramGuideDownloadService.onHandleIntent(ProgramGuideDownloadService.java:130)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by dmfrey** [comment]
# Google Play User Message

when downloading channel info I got a crash. I have lots of channels so is there a limit somewhere ?

**Comment by dmfrey** [comment]
Issue is due to this changes: http://www.oracle.com/technetwork/java/javase/compatibility-417013.html#source

Moving to MythTV Services API
