### ISSUE TITLE
Google Play Issue - Mythmote scan failed

### ISSUE THREAD

**Issue by dmfrey** [MythTV-Clients/MythTV-Android-Frontend#57]
java.lang.NullPointerException
at org.mythtv.client.ui.frontends.FrontendsFragment$ScanFrontendsTask.onPostExecute(FrontendsFragment.java:318)
at org.mythtv.client.ui.frontends.FrontendsFragment$ScanFrontendsTask.onPostExecute(FrontendsFragment.java:1)
at android.os.AsyncTask.finish(AsyncTask.java:602)
at android.os.AsyncTask.access$600(AsyncTask.java:156)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:615)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4424)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
at dalvik.system.NativeStart.main(Native Method)

**Comment by pot8oe** [comment]
I wasn't able to recreate but I added protection against null reference for context and AlertDialog used on FrontendsFragment.java:318.
